name: publish

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: build
        run: make build
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: files
          path: dist/
  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - release-build
    permissions:
      id-token: write
    environment:
      name: pypi
    steps:
      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          name: files
          path: dist/
      - name: publishing
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/